"""Core module: protocols, types, registry, constants, enums, domain types, and matrix."""

from hyesg.core.constants import (
    AKIMA_CSV_ROUND_PLACES,
    BLACK_IV_TOLERANCE,
    BOND_YTM_MAX_ITER,
    BOND_YTM_TOL,
    CIR_ZERO_H_THRESHOLD,
    CIR_ZERO_VOL_THRESHOLD,
    COMPOUNDING_PRECISION,
    CREDIT_RECOVERY_QUADRATURE_TOL,
    DEFAULT_RNG_SEED,
    GAUSS_KRONROD_BOUNDS_TOL,
    GAUSS_KRONROD_DEFAULT_TOL,
    GAUSS_KRONROD_MAX_DEPTH,
    INITIAL_YC_TARGET_COINCIDENCE_TOL,
    LIMIT_EPSILON,
    LM_DEFAULT_DAMPING,
    LM_DEFAULT_MAX_ITER,
    LM_DEFAULT_TOL,
    MIN_TRANSACTION,
    MIN_VALUE,
    NUMERICAL_DERIVATIVE_H,
    PARAMETRIC_CURVE_EPSILON,
    PORTFOLIO_BRENT_ITERS,
    PORTFOLIO_BRENT_TOL,
    REGIME_CHI2_SEED_FACTOR,
    REGIME_CHI2_SEED_OFFSET,
    REGIME_COPULA_SEED_OFFSET,
    REGIME_TRIAL_ORDERING_SEED_FACTOR,
    SHORTING_TEST,
    TIME_CONSISTENCY_PLACES,
    TIME_CONSISTENCY_ROUND,
    TIME_EPSILON,
    TIME_PLACES,
    VOLATILITY_PRECISION,
    YIELD_CURVE_EPSILON,
)
from hyesg.core.domain_types import (
    BondMetrics,
    CapAndFloor,
    Cashflow,
    CreditSpec,
    ForwardRate,
    Maturity,
)
from hyesg.core.enums import (
    CompoundingConvention,
    CreditClass,
    ExerciseType,
    Liquidity,
    PoissonDistributionType,
    RebalancingStrategy,
    RecoveryType,
)
from hyesg.core.protocols import (
    BondOptionPricing,
    CreditModel,
    CurrencyAnalogy,
    ExchangeRateModel,
    Model,
    Named,
    PortfolioModel,
    PostProcessor,
    ShortRateModel,
    StochasticProcess,
    SwaptionPricing,
    YieldCurveProtocol,
)
from hyesg.core.registry import (
    clear_registry,
    get_model,
    list_models,
    register_model,
)
from hyesg.core.matrix import (
    LabelledMatrix,
    SymmetricLabelledMatrix,
)
from hyesg.core.types import (
    CIR2State,
    CIRState,
    CreditState,
    FXState,
    G2State,
    JumpState,
    OUState,
    OutputSpec,
    PortfolioState,
    ShockConfig,
    SimulationState,
    TimeStep,
    VolState,
)

__all__ = [
    # constants
    "AKIMA_CSV_ROUND_PLACES",
    "BLACK_IV_TOLERANCE",
    "BOND_YTM_MAX_ITER",
    "BOND_YTM_TOL",
    "CIR_ZERO_H_THRESHOLD",
    "CIR_ZERO_VOL_THRESHOLD",
    "COMPOUNDING_PRECISION",
    "CREDIT_RECOVERY_QUADRATURE_TOL",
    "DEFAULT_RNG_SEED",
    "GAUSS_KRONROD_BOUNDS_TOL",
    "GAUSS_KRONROD_DEFAULT_TOL",
    "GAUSS_KRONROD_MAX_DEPTH",
    "INITIAL_YC_TARGET_COINCIDENCE_TOL",
    "LIMIT_EPSILON",
    "LM_DEFAULT_DAMPING",
    "LM_DEFAULT_MAX_ITER",
    "LM_DEFAULT_TOL",
    "MIN_TRANSACTION",
    "MIN_VALUE",
    "NUMERICAL_DERIVATIVE_H",
    "PARAMETRIC_CURVE_EPSILON",
    "PORTFOLIO_BRENT_ITERS",
    "PORTFOLIO_BRENT_TOL",
    "REGIME_CHI2_SEED_FACTOR",
    "REGIME_CHI2_SEED_OFFSET",
    "REGIME_COPULA_SEED_OFFSET",
    "REGIME_TRIAL_ORDERING_SEED_FACTOR",
    "SHORTING_TEST",
    "TIME_CONSISTENCY_PLACES",
    "TIME_CONSISTENCY_ROUND",
    "TIME_EPSILON",
    "TIME_PLACES",
    "VOLATILITY_PRECISION",
    "YIELD_CURVE_EPSILON",
    # domain types
    "BondMetrics",
    "CapAndFloor",
    "Cashflow",
    "CreditSpec",
    "ForwardRate",
    "Maturity",
    # enums
    "CompoundingConvention",
    "CreditClass",
    "ExerciseType",
    "Liquidity",
    "PoissonDistributionType",
    "RebalancingStrategy",
    "RecoveryType",
    # protocols
    "BondOptionPricing",
    "CreditModel",
    "CurrencyAnalogy",
    "ExchangeRateModel",
    "Model",
    "Named",
    "PortfolioModel",
    "PostProcessor",
    "ShortRateModel",
    "StochasticProcess",
    "SwaptionPricing",
    "YieldCurveProtocol",
    # registry
    "clear_registry",
    "get_model",
    "list_models",
    "register_model",
    # matrix
    "LabelledMatrix",
    "SymmetricLabelledMatrix",
    # types
    "CIR2State",
    "CIRState",
    "CreditState",
    "FXState",
    "G2State",
    "JumpState",
    "OutputSpec",
    "OUState",
    "PortfolioState",
    "ShockConfig",
    "SimulationState",
    "TimeStep",
    "VolState",
]
