"""Core module: protocols, types, registry, and constants."""

from hyesg.core.constants import (
    BLACK_IV_TOLERANCE,
    CIR_ZERO_H_THRESHOLD,
    CIR_ZERO_VOL_THRESHOLD,
    COMPOUNDING_PRECISION,
    DEFAULT_RNG_SEED,
    MIN_TRANSACTION,
    MIN_VALUE,
    NUMERICAL_DERIVATIVE_H,
    PARAMETRIC_CURVE_EPSILON,
    PORTFOLIO_BRENT_ITERS,
    PORTFOLIO_BRENT_TOL,
    SHORTING_TEST,
    TIME_EPSILON,
    TIME_PLACES,
    VOLATILITY_PRECISION,
    YIELD_CURVE_EPSILON,
)
from hyesg.core.protocols import (
    BondOptionPricing,
    CreditModel,
    CurrencyAnalogy,
    ExchangeRateModel,
    Model,
    Named,
    PortfolioModel,
    PostProcessor,
    ShortRateModel,
    StochasticProcess,
    SwaptionPricing,
    YieldCurveProtocol,
)
from hyesg.core.registry import (
    clear_registry,
    get_model,
    list_models,
    register_model,
)
from hyesg.core.types import (
    CIR2State,
    CIRState,
    CreditState,
    FXState,
    G2State,
    OUState,
    OutputSpec,
    PortfolioState,
    ShockConfig,
    SimulationState,
    TimeStep,
)

__all__ = [
    # constants
    "BLACK_IV_TOLERANCE",
    "CIR_ZERO_H_THRESHOLD",
    "CIR_ZERO_VOL_THRESHOLD",
    "COMPOUNDING_PRECISION",
    "DEFAULT_RNG_SEED",
    "MIN_TRANSACTION",
    "MIN_VALUE",
    "NUMERICAL_DERIVATIVE_H",
    "PARAMETRIC_CURVE_EPSILON",
    "PORTFOLIO_BRENT_ITERS",
    "PORTFOLIO_BRENT_TOL",
    "SHORTING_TEST",
    "TIME_EPSILON",
    "TIME_PLACES",
    "VOLATILITY_PRECISION",
    "YIELD_CURVE_EPSILON",
    # protocols
    "BondOptionPricing",
    "CreditModel",
    "CurrencyAnalogy",
    "ExchangeRateModel",
    "Model",
    "Named",
    "PortfolioModel",
    "PostProcessor",
    "ShortRateModel",
    "StochasticProcess",
    "SwaptionPricing",
    "YieldCurveProtocol",
    # registry
    "clear_registry",
    "get_model",
    "list_models",
    "register_model",
    # types
    "CIR2State",
    "CIRState",
    "CreditState",
    "FXState",
    "G2State",
    "OutputSpec",
    "OUState",
    "PortfolioState",
    "ShockConfig",
    "SimulationState",
    "TimeStep",
]
